name: Mosser
seeds:
  - https://www.mosserliving.com/neighborhoods/lower-haight
strategy_order:
  - xhr
  - dom
rate_limit: 1.0
xhr:
  endpoints:
    - https://www.mosserliving.com/api/listings/lower-haight.json
  unit_paths:
    - $.listings[*]
  field_map:
    title: $.title
    address: $.address
    beds: $.beds
    baths: $.baths
    rent_min: $.rent_min
    rent_max: $.rent_max
    url: $.url
dom:
  list_selector: ul.listing-grid li.listing
  field_selectors:
    title: h2
    beds: .beds
    baths: .baths
    rent: .rent
    sqft: .sqft
    url: ::attr(data-url)
  regex_helpers:
    rent: "\$(\\d+[\\,\\d]*)"
hints:
  neighborhood_from_seed:
    https://www.mosserliving.com/neighborhoods/lower-haight: Lower Haight
